blog/urls.py
from django.conf.urls import url

from .views import list_posts
from .views import view_post
from .views import create_post
from .views import edit_post
from .views import delete_post
from .views import create_comment
from .views import delete_comment


urlpatterns = [
    url(r'^posts/$', list_posts, name='list_posts'),
    url(r'^posts/(?P<pk>[0-9]+)/$', view_post, name='view_post'),
    url(r'^posts/create/$', create_post, name='create_post'),
    url(r'^posts/(?P<pk>[0-9]+)/edit/$', edit_post, name='edit_post'),
    url(r'^posts/(?P<pk>[0-9]+)/delete/$', delete_post, name='delete_post'),
    url(r'^posts/(?P<pk>[0-9]+)/create_comment/$', create_comment, name='create_comment'),
    url(r'^posts/(?P<pk>[0-9]+)/delete_comment/$', delete_comment, name='delete_comment')
]

instablog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.contrib.auth.views import login as django_login
from django.contrib.auth.views import logout as django_logout

from blog.urls import urlpatterns as blog_urls
from profiles.views import user_join

from blogtest.urls import urlpatterns as blogtest_urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include(blog_urls, namespace='blog')),
    url(r'^login/$', django_login, {'template_name':'login.html'}, name='login_url'), 
    url(r'^logout/$', django_logout, {'next_page':'/login/'}, name='logout_url'),
    url(r'^user_join/$', user_join, name='user_join_url'),
    url(r'^blogtest/', include(blogtest_urls, namespace='blogtest')),
]

blog/models.py
from django.db import models
from django.conf import settings

# from django.contrib.auth.models import AbstractUser
# 이렇게 쓰지말고 AbstractUser를 쓰세요
# class Profile(User):
#     pass


# class BasePost(models.Model):
#     title = models.CharField(max_length=200)
#     content = models.TextField()
#     category = models.ForeignKey('Category')
#     tags = models.ManyToManyField('Tag', blank=True)
    
#     class Meta:
#         abstract = True

class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, null=False)
    title = models.CharField(max_length=200)
    content = models.TextField()
    category = models.ForeignKey('Category')
    tags = models.ManyToManyField('Tag', blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '<Post {}: "{}">'.format(self.pk, self.title[:8])


class Category(models.Model):
    name = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '<Category {}:"{}">'.format(self.pk, self.name)


class Comment(models.Model):
    post = models.ForeignKey(Post)
    content = models.TextField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '<Comment {}>'.format(self.pk)


class Tag(models.Model):
    name = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '<Tag {}: "{}">'.format(self.pk, self.name)

blog/forms.py
# forms.py

from django import forms

from .models import Post


class PostForm(forms.ModelForm):
	# title = forms.CharField(widget=forms.PasswordInput)
	# 이 경우는 여기 선언된 title로 오버라이드 된다 

	def clean(self):
		title = self.cleaned_data.get('title', '')
		if '지각' in title:
			self.add_error('title', '지각자!!!')
		return None

	# def clean_title(self):
	# 	title = self.cleaned_data.get('title', '')
	# 	if '지각' in title:
	# 		raise forms.ValidationError(
	# 				'지각자 이름이 있습니다!', 
	# 				code='strange_word')
	#	return title

	class Meta:
		model = Post
		# fields = '__all__'
		fields = ('category', 'title', 'content', )
		# widgets = {
		# 	'title': forms.PasswordInput
		# }


class PostNormalForm(forms.Form):
	title = forms.CharField()
	content = forms.CharField(widget=forms.Textarea)
	email = forms.EmailField()
	category = forms.IntegerField(0)
	# registration_code = forms.CharField(
	# 	label = '주민번호', 
	# 	help_text = 'xxxxyyyy', 
	# 	widget = forms.TextInput(
	# 		attrs={'class': 'hello_world'}
	# 	)

blog/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect

from django.core.urlresolvers import reverse
from django.core.paginator import Paginator
from django.core.paginator import EmptyPage
from django.core.paginator import PageNotAnInteger

from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .models import Post
from .models import Category
from .models import Comment
from .forms import PostForm


def delete_comment(request, pk):
    comment = get_object_or_404(Comment, pk=pk)
    post = comment.post
    comment.delete()
    return redirect('blog:view_post', post.pk)

def create_comment(request, pk):
    if request.method == 'POST':
        form = request.POST
        post = get_object_or_404(Post, pk=pk)
        comment = Comment(
            post=post,
            content=form['comment']
            )
        comment.save()
        return redirect('blog:view_post', pk)

    return view_post(request, pk)

@login_required
def delete_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == 'POST':
        post.delete()
        return redirect('blog:list_posts')

    return render(request, 'delete.html', {
        'post': post
        })


@login_required
def edit_post(request, pk):
    messages.add_message(request, messages.ERROR, '포스트 수정중')
    post = get_object_or_404(Post, pk=pk)

    if request.method == 'GET':
        form = PostForm(instance=post)
    else:
        form = PostForm(request.POST)

        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('blog:view_post', pk=post.pk)

    categories = Category.objects.all()
    ctx = {
        'categories': categories,
        'form': form
    }
    return render(request, 'edit.html', ctx)

# def edit_post(request, pk):
#     if request.method == 'GET':
#         post = get_object_or_404(Post, pk=pk)
#         categories = Category.objects.all()
#     else:
#         return create_post(request)

#     return render(request, 'edit.html', {
#         'post': post, 
#         'categories': categories
#         })

# def create_post(request):
#     if request.method == 'GET':
#         form = PostForm()
#         categories = Category.objects.all()
#         ctx = {
#             'categories': categories,
#             'form': form
#         }
#     elif request.method == 'POST':
#         form = PostForm(request.POST)
#         if form.is_valid():
#             Post(
#                 title=form.cleaned_data['title'],
#                 content=form['content'],
#                 )
#             post.save()
#             return retirect('blog:view_post', pk=post.pk)

#     return render(request, 'edit.html', {
#         'form': form,})

@login_required
def create_post(request):

    # if not request.user.is_authenticated():
    #     raise Exception('님 로그인 안함.')

    # messages.add_message(request, messages.ERROR, '메시지 테스트!!')
    # messages.add_message(request, messages.INFO, '메시지 테스트!!')

    if request.method == 'GET':
        form = PostForm()
        
    else:
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            return redirect('blog:view_post', pk=post.pk)

    categories = Category.objects.all()
    ctx = {
        'categories': categories,
        'form': form
    }
    return render(request, 'edit.html', ctx)

def list_posts(request):
    page = request.GET.get('page', 1)
    per_page = 5

    posts = Post.objects.order_by('-created_at')
    pg = Paginator(posts, per_page)

    try:
        contents = pg.page(page)
    except PageNotAnInteger:
        contents = pg.page(1)
    except EmptyPage:
        contents = []

    return render(request, 'list.html', {
        'posts': contents,
        })


def view_post(request, pk):
    if request.method == 'POST':
        form = request.POST
        post = get_object_or_404(Post, pk=pk)
        comment = Comment(
            post=post,
            content=form['comment']
            )
        comment.save()
        url = reverse('blog:view_post', kwargs={'pk':pk})
        return redirect(url)
    
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'view.html', {
        'post': post
        })

blog/templates/blog_layout.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="ko">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> {% block page_title %}Instablog{% endblock %}</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}

</head>

<body>

<div class="container">

<p>
<h1 class="blog_name">{ INSTABLOG }</h1>

<a href="{% url 'blog:list_posts' %}" class="btn btn-primary">글 목록</a>
<a href="{% url 'blog:create_post' %}" class="btn btn-primary">새 글</a>

{# {% bootstrap_button content="글 목록" button_type="link" button_class="btn-primary" icon="" %} #}

{# {% bootstrap_button content="새 글" button_type="link" button_class="" icon="" %} #}
</p>

{% block header %}{% endblock %}

{% block body %}{% endblock %}

</div>

</body>
</html>

blog/templates/comment_list.html
{% load bootstrap3 %}
<div class="comments_container">
    {% for comment in post.comment_set.all %}
    <div class="comment_container">
    
        <div class="comment_content pull-left">
            {{comment.content}}
        </div>

        <form method="POST" action="{% url 'blog:delete_comment' comment.pk %}" class="pull-left">
        {% csrf_token %}
        {% bootstrap_button content="" button_type="submit" button_class="close" icon="remove" %}
        </form>
        <p class="clearfix"></p>
        <p><span>작성일시</span>{{comment.created_at}}</p>
    
    </div>
    
    {% empty %}
        <p>댓글이 없습니다</p>
    {% endfor %}
</div>

<form method="POST" action="{% url 'blog:create_comment' post.pk %}">
    {% csrf_token %}
    <p>
        <input type="text" name="comment" value="" class="form_control" placeholder="댓글을 입력하세요..."/>
        <input type="submit" value="submit" />
    </p>
</form>

blog/templates/delete.html
<h3>{{post.title}}</h3>
<form method="POST" action="">
    {% csrf_token %}
    <p>
    정말로 지우시겠습니까?
    </p>

    <p>
        <input type="submit" value="삭제" />
    </p>
</form>

blog/templates/edit.html
{% extends 'blog_layout.html' %}
{% load bootstrap3 %}

{% block page_title %}글 작성 {% endblock %}

{% block body %}

{% if post %}
<h3>{{post.title}} 고치기</h3>
{% endif %}

{% if messages %}
{% for message in messages %}
    <div class="alert{% if message.tags %} alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %}{% endif %} alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&#215;</button>
        {{ message|safe|urlize|linebreaksbr }}
    </div>
{% endfor %}
{% endif %}

{% if form.title.errors or form.content.errors or form.emal.errors %}
<p> 님하 뭔가 잘못..</p>
{% endif %}

<form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    <p>
        {% bootstrap_button "저장" button_type="submit" button_class="btn-primary" %}
    </p>
</form>

{% endblock %}

blog/templates/list.html
{% extends 'blog_layout.html' %}
{% load bootstrap3 %}

{% block page_title %}글 목록{% endblock %}

{% block body %}

{% for post in posts %}

    <div class="post_container">
        <h3 class="post_title">
            <a href="{% url 'blog:view_post' post.pk %}">{{post.title}}</a>
            
        </h3>
        <div class="post_conent">{{post.content}}</div>
    </div>

    <div>
        <p><span>카테고리:</span>{{post.category.name}} 
        <span>작성:</span>{{post.created_at}} </p>
    </div>



{% empty %}
    <p>글이 하나도 없습니다</p>
{% endfor %}

{% bootstrap_pagination posts %}

{% endblock %}

blog/templates/view.html
{% extends 'blog_layout.html' %}
{% load bootstrap3 %}

{% block page_title %}글 보기 : {{post.title}}{% endblock %}

{% block body %}

<div class="post_container">
    <h3 class="post_title">{{post.title}}</h3>
    <div class="post_content">{{post.content}}</div>
    <div>
        <p><span>글 갈래</span>{{post.category.name}}</p>
        <p><span>작성일시</span>{{post.created_at}}</p>
    </div>
</div>

<hr/>
{% with comments=post.comment_set.all %}
    {% include 'comment_list.html' %}
{% endwith %}

<div>
    <p><a href="{% url 'blog:edit_post' post.pk %}"> 글 수정</a></p>
</div>

{% endblock %}